### ISSUE TITLE
[feature] Darken loading screen?

### ISSUE THREAD

**Issue by olee** [markviews/LoadingScreenPictures#7]
Do you think it might be possible to add a small option for this mod to replace the colors of the loading screen (the bright blue) to give it some darker color scheme to make it more easygoing for the eyes?

I can also see that this might not belong into this mod / should be a separate mod, but I thought it might be a nice addition.

**Comment by markviews** [comment]
sorry for the late response. I thought there was a mod that did this but I can't find it 🤷‍♂️
I'll add this feature soon

**Comment by markviews** [comment]
i'll try to get to this in the next few days. For now you could check out emmvrc, it lets you color the green background.

**Comment by markviews** [comment]
Sorry I should have replied to this a while ago, I don't plan to add this feature to this mod, I'm pretty busy with school :)
